# Generated by Django 4.2.30 on 2026-08-18 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_refund_item_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='refund_proofs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.refund')),
            ],
        ),
    ]
