# Generated by Django 4.2.30 on 2026-06-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Tamilnadu', max_length=50)),
                ('delivery_type', models.CharField(choices=[('same_day', 'Same Day'), ('standard', 'Standard'), ('none', 'Not Available')], default='standard', max_length=20)),
                ('estimated_days_text', models.CharField(blank=True, max_length=50)),
                ('store_pickup_available', models.BooleanField(default=False)),
                ('cod_available', models.BooleanField(default=True)),
                ('delivery_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
