# Generated by Django 4.2.30 on 2026-08-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsideStateDeliveryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_charge', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('estimated_days_text', models.CharField(default='5-8 business days', max_length=50)),
                ('cod_available', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='If off, orders outside Tamil Nadu are rejected at checkout')),
            ],
            options={
                'verbose_name': 'Outside Tamil Nadu delivery rate',
                'verbose_name_plural': 'Outside Tamil Nadu delivery rate',
            },
        ),
    ]
