# Generated by Django 4.2.30 on 2026-08-04 08:47

from django.db import migrations, models

# Same-day delivery is not offered. The tier is kept, renamed to 'local', purely
# as a price zone so Chennai-metro pincodes keep their cheaper Rs.30 rate -
# mapping them to 'standard' instead would have quietly raised it to Rs.80.
# Estimates move to the shipping policy's stated figure for Tamil Nadu.
TAMIL_NADU_ESTIMATE = '2-4 business days'


def same_day_to_local(apps, schema_editor):
    DeliveryPincode = apps.get_model('delivery', 'DeliveryPincode')
    DeliveryPincode.objects.filter(delivery_type='same_day').update(
        delivery_type='local', estimated_days_text=TAMIL_NADU_ESTIMATE,
    )
    # 'Today' could also have been set by hand on a standard pincode.
    DeliveryPincode.objects.filter(estimated_days_text__iexact='Today').update(
        estimated_days_text=TAMIL_NADU_ESTIMATE,
    )
    DeliveryPincode.objects.filter(estimated_days_text='2-3 days').update(
        estimated_days_text=TAMIL_NADU_ESTIMATE,
    )


def local_to_same_day(apps, schema_editor):
    DeliveryPincode = apps.get_model('delivery', 'DeliveryPincode')
    DeliveryPincode.objects.filter(delivery_type='local').update(
        delivery_type='same_day', estimated_days_text='Today',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_outsidestatedeliveryrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypincode',
            name='delivery_type',
            field=models.CharField(choices=[('local', 'Local (Chennai metro)'), ('standard', 'Standard'), ('none', 'Not Available')], default='standard', max_length=20),
        ),
        migrations.RunPython(same_day_to_local, local_to_same_day),
    ]
