# Generated by Django 4.2.30 on 2026-08-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_rename_same_day_to_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamilNaduDeliveryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_charge', models.DecimalField(decimal_places=2, default=30, help_text='Charge for pincodes on the "Local (Chennai metro)" zone.', max_digits=10)),
                ('standard_charge', models.DecimalField(decimal_places=2, default=80, help_text='Charge for pincodes on the "Standard" zone.', max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=500, help_text='Order subtotal at or above which Tamil Nadu delivery is free.', max_digits=10)),
                ('weight_surcharge_per_500g', models.DecimalField(decimal_places=2, default=10, help_text='Added per 500g (or part of) above the weight allowance.', max_digits=10)),
                ('weight_allowance_g', models.PositiveIntegerField(default=1000, help_text='Order weight in grams before the surcharge starts applying.')),
                ('estimated_days_text', models.CharField(default='2-4 business days', help_text='Fallback estimate for pincodes with none of their own.', max_length=50)),
            ],
            options={
                'verbose_name': 'Tamil Nadu delivery rate',
                'verbose_name_plural': 'Tamil Nadu delivery rate',
            },
        ),
        migrations.AddField(
            model_name='outsidestatedeliveryrate',
            name='weight_allowance_g',
            field=models.PositiveIntegerField(default=1000, help_text='Order weight in grams before the surcharge starts applying.'),
        ),
        migrations.AddField(
            model_name='outsidestatedeliveryrate',
            name='weight_surcharge_per_500g',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Added per 500g (or part of) above the weight allowance.', max_digits=10),
        ),
    ]
