# Generated by Django 4.2.30 on 2026-06-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_g',
            field=models.IntegerField(default=500, help_text='Weight in grams'),
        ),
    ]
