# Generated by Django 4.2.30 on 2026-08-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_weight_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_devices',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of compatible devices'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='', help_text='e.g. "6 months" (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='age_group',
            field=models.CharField(blank=True, default='', help_text='Kids\' Wear only, e.g. "2-4Y"', max_length=30),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='fabric',
            field=models.CharField(blank=True, choices=[('cotton', 'Cotton'), ('linen', 'Linen'), ('viscose', 'Viscose'), ('denim', 'Denim'), ('polyester', 'Polyester'), ('rayon', 'Rayon'), ('blend', 'Blend'), ('others', 'Others')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='fit',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('slim', 'Slim'), ('oversized', 'Oversized'), ('relaxed', 'Relaxed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='shade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='volume',
            field=models.CharField(blank=True, default='', help_text='e.g. "30ml", "100ml"', max_length=30),
        ),
    ]
