# Generated by Django 4.2.30 on 2026-08-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_batch_number_product_care_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='large',
            field=models.ImageField(blank=True, editable=False, upload_to='products/large/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='medium',
            field=models.ImageField(blank=True, editable=False, upload_to='products/medium/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='small',
            field=models.ImageField(blank=True, editable=False, upload_to='products/small/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumb',
            field=models.ImageField(blank=True, editable=False, upload_to='products/thumb/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/original/'),
        ),
    ]
