# Generated by Django 4.2.30 on 2026-08-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_large_productimage_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='occasion',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('party', 'Party'), ('ethnic', 'Ethnic')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='skin_type',
            field=models.CharField(blank=True, default='', help_text='Optional, e.g. "Oily", "Dry", "All"', max_length=30),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sleeve_type',
            field=models.CharField(blank=True, choices=[('half_sleeve', 'Half Sleeve'), ('full_sleeve', 'Full Sleeve')], default='', max_length=20),
        ),
    ]
