# Generated by Django 4.2.30 on 2026-08-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytransaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
    ]
