# Generated by Django 4.2.30 on 2026-08-02 06:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_loyaltytransaction_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_100_spent', models.PositiveIntegerField(default=1, help_text='Points earned per Rs.100 of order subtotal')),
                ('point_value_rupees', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Rupee value of 1 point when redeemed at checkout', max_digits=6)),
                ('validity_days', models.PositiveIntegerField(default=365, help_text='Days after earning before a batch of points expires')),
                ('max_redeem_percent', models.PositiveIntegerField(default=20, help_text='Max % of order subtotal payable with points, per order')),
                ('welcome_bonus_points', models.PositiveIntegerField(default=50)),
                ('referral_bonus_points', models.PositiveIntegerField(default=50, help_text='Given to both the referrer and the new user')),
                ('birthday_bonus_points', models.PositiveIntegerField(default=100)),
                ('expiring_soon_window_days', models.PositiveIntegerField(default=30, help_text='Window used for the "expiring soon" balance warning')),
            ],
            options={
                'verbose_name': 'Loyalty program configuration',
                'verbose_name_plural': 'Loyalty program configuration',
            },
        ),
    ]
