# Generated by Django 4.2.30 on 2026-08-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_reviews', models.BooleanField(default=True, help_text='On: new reviews go live immediately. Off: every new review is held as pending and only appears on the product page once staff approve it in the Reviews list.')),
            ],
            options={
                'verbose_name': 'Review moderation configuration',
                'verbose_name_plural': 'Review moderation configuration',
            },
        ),
    ]
